// * MULTIPLY OPERATOR DO NO CONCATINATE THE BOTH SIDES VARIABLES VALUE. IF ONE VARIABLE VALUE IS A STRING TYPE AND ONE VARIABLE VALUE IS A NUMBER AND IF WE PERFROM MULTIPICATION THEN THE OUTPUT IS NaN. 

var x;
x="uday";
var y=20;
z=x*y;
console.log(z);

//BUT IF ONE SIDE VARIBALE IS A STRING AND IN STRING A NUMBER IS STORED THEN IS PERFORMS MULTIPLICATION.

var g="20";
var f=100;
var u=g*f;
console.log(u);