// Divide / OPERATOR DO NO CONCATINATE THE BOTH SIDES VARIABLES VALUE. IF ONE VARIABLE VALUE IS A STRING TYPE AND ONE VARIABLE VALUE IS A NUMBER AND IF WE PERFROM MULTIPICATION THEN THE OUTPUT IS NaN. BUT ONE SIDE VARIABLE VALUE IS A STRING AND IN STRING THERE IS A NUMBER STORED THEN IT PERFORMS DIVIDE.

var y="10";
var x=2;
var z=y/x;
console.log(z); 
