var y=[45,78,64,65,458];
var x=y.sort((i,j)=>i-j ); //I GIVE A FUNCTION TO SORT AND IT RETURNS THE VALUE, IF THE VALUE IF IN - THEN IT CONSIDER AS j IS GREATER THAN i, THEN SORT FUNCTION SWAP IT. 
console.log(x);