var a={x:100,y:20}
var b={x:10,z:30}
var c={...a,...b} //EXTRACTING THE VALUES OF OBJECT a AND b BY USING SPREAD SYNTAX. 
console.log(c); //BUT IN OBJECT a AND b HAS SAME VALUES OF x, IN C THERE IS ONLY ONE x AND THERE VALUE IS 10 BEACUSE LAST TIME THE VALUE HAS BEEN SPEFICED IT IS CONSIDER AS FINAL VALUE. 



